'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roles={user:'普通用户',operator:'运维人员',engineer:'工程师',librarian:'知识管理员',admin:'系统管理员'};
const level={user:0,operator:0,engineer:1,librarian:2,admin:3};
const rolePages={
  user:['chat','knowledge'],
  operator:['chat','knowledge'],
  engineer:['chat','knowledge','pipeline'],
  librarian:['chat','knowledge','pipeline','audit'],
  admin:['overview','chat','knowledge','pipeline','access','audit']
};
function visiblePages(){
  if(!window.WIND_DEMO){const common=['dashboard','farms','turbines','data','analysis','prediction','monitoring','alerts','maintenance','reports','chat','knowledge','preferences'];return state.user?.role==='admin'?[...common,'imports','users','access','logs','pipeline','overview']:['engineer','librarian'].includes(state.user?.role)?[...common,'pipeline']:common;}
  const pages=rolePages[state.user?.role]||[];
  return window.WIND_DEMO?[...new Set(['overview',...pages,'pipeline','access'])]:pages;
}
const moduleGroups=[
  ['驾驶舱与设备总览',['dashboard','farms','turbines','monitoring']],
  ['数据中心',['data','imports']],
  ['分析与功率预测',['analysis','prediction']],
  ['监测预警',['alerts']],
  ['运维与报表',['maintenance','reports']],
  ['知识问答与权限',['chat','knowledge','pipeline','overview','preferences','users','access','logs']]
];
const pageName=page=>window.Ops?.titles[page]||({chat:'知识问答',knowledge:'知识库',access:'角色与权限',pipeline:'RAG 链路',overview:'项目概览',audit:'审计记录'})[page]||page;
function renderNavigation(){
 if(window.WIND_DEMO)return;
 const allowed=visiblePages();
 $('#navigation').innerHTML=moduleGroups.map(([title,pages],i)=>{
  const items=pages.filter(p=>allowed.includes(p));if(!items.length)return '';
  return `<details class="nav-module" ${items.includes(state.page)?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span>${title}</summary><div>${items.map(page=>`<button data-page="${page}">${pageName(page)}</button>`).join('')}</div></details>`;
 }).join('');
 $$('#navigation [data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
}
function updateNavigation(){
 $$('#navigation [data-page]').forEach(button=>{button.hidden=!visiblePages().includes(button.dataset.page)});
}
const statusText={published:'已发布',staged:'待审核',retired:'历史版本'};
const state={user:null,page:'chat',docs:[],history:[],messages:[],last:null,farm:'',mode:'',busy:false};
let toastTimer;
function toast(message,error=false){const box=$('#toast');box.textContent=message;box.className='toast'+(error?' error':'');box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.hidden=true,4500)}
async function api(path,body){
  if(window.WIND_DEMO)return structuredClone(await demoAPI(path,body));
  let res;try{res=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-WindRAG':'1'},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch{throw Error('无法连接系统服务，请运行启动系统.cmd，并打开启动窗口显示的地址')}
  const result=await res.json();if(!res.ok){if(res.status===401&&path!=='login'){showLogin()}throw Error(result.error||'请求失败')}return result;
}
function showLogin(){$('#login').hidden=false;$('#app').hidden=true;state.user=null}
function dialog(title,html){$('#dialog').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button data-close aria-label="关闭">✕</button></div><div class="dialog-body">${html}</div>`;$('#dialog').showModal();$('#dialog [data-close]').onclick=()=>$('#dialog').close()}
function heading(title,subtitle,action=''){return `<div class="page-heading"><div><span class="eyebrow">WIND KNOWLEDGE / ${state.page.toUpperCase()}</span><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
async function boot(){if(!window.WIND_DEMO&&new URLSearchParams(location.search).get('login')==='1'){const url=new URL(location.href);url.searchParams.delete('login');history.replaceState(null,'',url.pathname+url.search+url.hash);showLogin();return}try{const me=await api('me');state.user=me.user;state.mode=me.mode;state.retrieval=me.retrieval;state.thresholds=me.thresholds;state.classifier=me.classifier||'BERT 未加载 · 规则分流';$('#login').hidden=true;$('#app').hidden=false;$('#userName').textContent=state.user.name;$('#userRole').textContent=roles[state.user.role];$('#modeBadge').textContent=(window.WIND_DEMO?'本地演示 · ':'')+'FAQ + '+me.mode;if(!window.WIND_DEMO){renderNavigation();$('#modeBadge').textContent='风电数据与知识服务';$('#alertBadge').hidden=false;$('#alertBadge').onclick=()=>navigate('alerts');api('ops/alerts?size=1&status='+encodeURIComponent('未处理')).then(d=>{$('#alertBadge').textContent='未处理告警 '+d.total}).catch(()=>{})}updateNavigation();
  if(window.WIND_DEMO){$('#demoRoleControl').hidden=false;$('#demoRole').hidden=false;$('#demoRole').innerHTML=Object.entries(roles).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('#demoRole').value=state.user.role;$('#logoutButton').textContent='重新演示'}else{$('#demoRoleControl').hidden=true;$('#demoRole').hidden=true;$('#logoutButton').textContent='退出登录'}
  state.history=(await api('history')).items;await navigate(window.WIND_DEMO?'overview':(visiblePages().includes(location.hash.slice(1))?location.hash.slice(1):'dashboard'));
}catch(e){if(window.WIND_DEMO){toast('演示加载失败：'+e.message,true);return}showLogin();$('#loginError').textContent=e.message||'登录后加载失败，请刷新重试'}}
async function navigate(page){if(state.navigating)return toast('页面正在加载，请稍候');if(!visiblePages().includes(page)){toast('当前角色无权访问此页面',true);return}if(state.busy)return toast('正在回答，请稍候');state.navigating=true;state.page=page;renderNavigation();if(!window.WIND_DEMO)history.replaceState(null,'','#'+page);$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent={overview:'项目概览',chat:'知识问答',knowledge:'知识库',pipeline:'链路与版本',access:'角色与权限',audit:'审计记录'}[page]||window.Ops?.titles[page];try{if(!window.WIND_DEMO&&window.Ops?.titles[page]){await Ops.render(page);return}await ({overview:renderOverview,chat:renderChat,knowledge:renderKnowledge,pipeline:renderPipeline,access:renderAccess,audit:renderAudit}[page])()}catch(e){toast(e.message,true)}finally{state.navigating=false}}
function renderOverview(){

  $('#pageContent').innerHTML=`<div class="page overview-page">${heading('风知 · 风电知识与协作系统','面向风场运维、工程分析与知识管理，将分散资料转化为可查询、可追溯、可授权的知识服务。','<button class="primary" id="overviewChat">进入知识问答 ↗</button>')}<div class="overview-tabs" role="tablist" aria-label="项目概览"><button id="introTab" role="tab" aria-controls="overviewBody" data-overview="intro">01 项目介绍</button><button id="backgroundTab" role="tab" aria-controls="overviewBody" data-overview="background">02 项目背景</button><button id="architectureTab" role="tab" aria-controls="overviewBody" data-overview="architecture">03 项目架构</button></div><div id="overviewBody" role="tabpanel"></div></div>`;
  $('#overviewChat').onclick=()=>navigate('chat');
  const tabs=$$('[data-overview]');
  tabs.forEach((button,index)=>{button.onclick=()=>paintOverview(button.dataset.overview);button.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(index+(e.key==='ArrowRight'?1:2))%3;tabs[next].click();tabs[next].focus()}});
  paintOverview('intro');
}
function paintOverview(kind){
  $$('[data-overview]').forEach(b=>{const selected=b.dataset.overview===kind;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});
  $('#overviewBody').setAttribute('aria-labelledby',{intro:'introTab',background:'backgroundTab',architecture:'architectureTab'}[kind]);
  const intro=`<section class="overview-intro"><div class="overview-intro-copy"><span class="eyebrow">项目定位</span><h2>把风电资料，<br>变成能找到依据的回答。</h2><p>风知是一个面向风力发电业务的 RAG 知识服务系统。它将机组说明、巡检制度、告警核对资料和工程文档纳入统一知识库，在用户提问时先筛选有权访问的有效资料，再检索证据并组织回答。</p><p>系统围绕“查知识、看来源、管版本、分权限”展开，让运维人员便捷查询，让工程师沉淀经验，让知识管理员维护资料质量，让系统管理员分配账号与风场范围。</p></div><aside class="overview-position"><span class="eyebrow">RAG 如何发挥作用</span><div><b>检索 Retrieval</b><p>从授权且有效的知识中找到相关片段。</p></div><div><b>增强 Augmentation</b><p>为问题补充来源、适用条件和文档版本。</p></div><div><b>生成 Generation</b><p>接入模型后依据证据生成回答；未接入时直接展示原文摘录。</p></div></aside></section><div class="overview-section-title"><span>核心服务</span><h2>从一次查询，到持续维护。</h2></div><div class="overview-capabilities"><article><span>01 / 问答</span><h3>有依据的知识查询</h3><p>围绕部件原理、告警信息、巡检记录和统计口径提问，查看引用片段、资料版本与个人问答历史。</p></article><article><span>02 / 治理</span><h3>有版本的知识维护</h3><p>将文本资料导入为候选版本，经检查和审核后发布；修订保留历史，必要时回滚有效版本。</p></article><article><span>03 / 协作</span><h3>有边界的角色分工</h3><p>运维查询、工程修订、知识审核、系统授权分工明确，同时按风场范围隔离资料访问。</p></article></div><section class="overview-example"><div><span class="eyebrow">一次典型使用</span><h3>“风机出现温度告警，先核对哪些信息？”</h3></div><p>运维人员选择风场后提问 → 系统检索可见的告警核对资料 → 返回需补充的机组、告警与工况信息 → 展示原文来源 → 用户反馈需要复核的内容。</p><button id="overviewExample">用这个问题体验问答 ↗</button></section>`;
  const background=`<section class="overview-background-lead"><span class="eyebrow">建设背景</span><h2>资料分散、条件不同，<br>知识查询需要同时解决“找得到”和“用得对”。</h2><p>风场运维涉及设备说明、告警记录、巡检制度与工程分析等多种资料。不同机型、风场和文件版本可能有不同的适用条件，查到相似表述并不意味着可以直接用于当前问题。系统因此需要把来源、版本与访问范围一起纳入检索过程。</p><p>只做普通聊天，难以核对答案依据；只做文件存放，又需要人员反复翻找和比较。风知把文档检索与问答结合起来，同时加入审核发布、权限过滤和反馈记录，服务于日常知识查询与资料维护。</p></section><div class="overview-section-title"><span>问题与目标</span><h2>每个建设目标，都对应具体业务问题。</h2></div><div class="background-matrix"><div class="background-matrix-head"><span>业务问题</span><span>建设目标</span><span>验证方式</span></div>${[
    ['资料分散，查找反复','说明书、制度与分析资料需要分别检索，相关上下文容易遗漏。','让查询聚焦相关证据','统一入库，按问题检索片段，并提供原文入口。','用典型问题核对命中片段与引用来源，检查有无遗漏必要条件。'],
    ['机型与版本差异','相近问题可能适用不同资料，历史文件不应直接替代当前有效规则。','让回答保留适用条件','按风场、有效期和发布版本过滤；缺少机型信息时继续核实。','检查候选、历史与过期资料不会进入有效问答；核对答案适用范围。'],
    ['资料权限不同','普通运维资料与工程文档的可见范围不同，不能只靠页面按钮控制。','让访问同时满足角色与风场','服务端先判断权限，再进行检索与知识操作。','用跨风场查询、受限文档提问和越权发布验证拦截结果。'],
    ['经验更新缺少留痕','资料修订与问答反馈需要关联版本，便于后续维护和复核。','让知识持续更新、过程可追溯','保存候选、审核、历史版本与问答引用快照。','走通导入、发布、修订、回滚和反馈记录，核对变更后的生效资料。']
  ].map(([problem,detail,goal,method,check])=>`<article><div><small>业务问题</small><h3>${problem}</h3><p>${detail}</p></div><div><small>建设目标</small><h3>${goal}</h3><p>${method}</p></div><div><small>验证方式</small><p>${check}</p></div></article>`).join('')}</div><div class="overview-boundary"><b>系统定位</b><p>提供知识检索、证据整理与资料管理支持。实时状态由授权监控系统提供；现场控制、检修决策和工作许可仍由具备相应职责的人员按有效规程执行。</p></div>`;
  const architecture=`<section class="overview-architecture-intro"><div><span class="eyebrow">总体架构</span><h2>一个工作台，两条知识链路，<br>统一的权限与数据边界。</h2></div><p>前端提供问答和知识管理入口；后端统一校验身份与范围，分别处理在线检索、离线版本治理和账号审计。文本、片段、引用与操作记录存入 SQLite，模型能力通过可选接口接入。</p></section><div class="overview-architecture" aria-label="运行版系统逻辑架构"><div class="architecture-layer"><span class="layer-label">01 交互层</span><div class="architecture-cells"><article><h3>知识服务前端</h3><p>问答 · 来源查看 · 本人历史 · 反馈</p></article><article><h3>管理前端</h3><p>知识库 · 候选审核 · 版本回滚 · 账号权限</p></article></div></div><div class="architecture-connector">↓ <span>同源 HTTP / JSON 请求</span></div><div class="architecture-gateway"><span>02 接入与权限</span><h3>Python HTTP 服务 · 会话认证与访问校验</h3><p>账号身份 → 角色能力 → 风场范围 → 资料有效性；写操作增加来源校验</p></div><div class="architecture-connector">↓ <span>按任务分流，后端执行权限检查</span></div><div class="architecture-layer"><span class="layer-label">03 业务编排</span><div class="architecture-cells three"><article><h3>在线问答服务</h3><p>上下文处理 → 授权过滤<br>FAQ 命中直出 / 未命中检索<br>证据整理 → 答案与引用</p></article><article><h3>离线知识服务</h3><p>文本导入 → 候选版本<br>切分与索引完整性检查<br>审核发布 → 历史与回滚</p></article><article><h3>权限与记录服务</h3><p>账号创建 · 风场分配<br>本人问答历史与反馈<br>知识变更和登录审计</p></article></div></div><div class="architecture-connector">↕ <span>读写知识与业务记录 / 调用可选模型接口</span></div><div class="architecture-layer"><span class="layer-label">04 数据与模型</span><div class="architecture-cells"><article class="storage-cell"><h3>本地 SQLite 持久化</h3><p>用户 / 会话 / 文档版本 / 知识片段<br>向量缓存 / 问答引用 / 反馈 / 审计</p></article><article class="model-cell"><h3>可选模型接口</h3><p>BERT：意图分类（需训练权重）<br>Embedding：语义向量与 BM25 融合<br>LLM：基于证据生成带引用回答</p></article></div></div></div><div class="overview-architecture-foot"><p><b>权限先于检索：</b>无权访问的资料不会进入候选证据，也不会发送给配置的模型服务。</p><p><b>两种运行方式：</b>未接模型时使用 BM25 与原文摘录；配置兼容接口后启用语义检索和生成。单文件演示版在浏览器模拟交互，真实权限由运行版后端执行。</p></div><div class="overview-tech-strip"><div><b>前端</b><span>HTML / CSS / JavaScript</span></div><div><b>后端</b><span>Python 标准库 HTTP 服务</span></div><div><b>检索与存储</b><span>BM25 / 相关度门槛 / SQLite</span></div><div><b>模型接入</b><span>兼容 Embeddings / Chat API</span></div></div><div class="overview-actions"><button id="overviewPipeline">查看在线 / 离线详细链路 →</button><button id="overviewAccess">查看角色权限矩阵 →</button></div>`;
  $('#overviewBody').innerHTML={intro,background,architecture}[kind];
  if($('#overviewExample'))$('#overviewExample').onclick=async()=>{await navigate('chat');await sendQuestion('风机出现温度告警，需要核对哪些信息？')};
  if($('#overviewPipeline'))$('#overviewPipeline').onclick=()=>navigate('pipeline');
  if($('#overviewAccess'))$('#overviewAccess').onclick=()=>navigate('access');
}
async function renderChat(){
  $('#pageContent').innerHTML=`<div class="page">${heading('让风电知识，随问随到。','从设备原理到运维记录，检索授权资料，并保留每一条回答的来源。')}<div class="chat-layout"><section class="chat-panel"><div class="chat-toolbar"><div><label for="farmScope">知识范围</label><select id="farmScope"><option value="">全部授权风场</option>${state.user.farms.map(f=>`<option>${esc(f)}</option>`).join('')}</select></div><button id="newChat">＋ 新对话</button></div><div id="conversation" class="conversation" aria-live="polite"></div><form id="chatForm" class="composer"><div class="input-wrap"><textarea id="question" aria-label="输入风电知识问题" placeholder="例如：风机告警分析前，需要先核对哪些信息？" maxlength="2000" rows="2" required></textarea><button class="primary" type="submit" id="sendButton">发送 ↑</button></div><div class="composer-footer"><span>Enter 发送 · Shift + Enter 换行</span><span>知识问答不执行机组控制操作</span></div></form></section><aside class="side-stack"><section class="side-card"><div class="side-label"><h3>引用资料</h3><span id="sourceCount">0 份</span></div><div id="sources"></div></section><section class="side-card"><div class="side-label"><h3>本次问答链路</h3><span>TRACE</span></div><ol id="trace" class="trace-list"></ol></section><section class="side-card"><div class="side-label"><h3>最近问答</h3><span>仅本人可见</span></div><div id="historyList"></div></section></aside></div></div>`;
  $('#pageContent .page').insertAdjacentHTML('beforeend','<section class="panel query-metrics"><div class="panel-title"><h2>本次判断与检索数据</h2><span class="badge grey">实际计算 · 非准确率</span></div><div id="metricsSummary"></div><details id="metricsDetails"><summary>查看候选资料、得分与淘汰原因</summary><div id="metricTable" class="table-wrap"></div></details></section>');
  $('#farmScope').value=state.farm;$('#farmScope').onchange=e=>{if(state.busy){e.target.value=state.farm;return toast('正在回答，请稍候')}state.farm=e.target.value;state.last=null;state.messages=[];renderChat()};
  $('#chatForm').onsubmit=e=>{e.preventDefault();sendQuestion()};$('#question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendQuestion()}};
  $('#newChat').onclick=()=>{if(state.busy)return;state.messages=[];state.last=null;renderMessages();$('#question').focus()};renderMessages();renderHistory();
}
function renderMessages(){
  const panel=$('#conversation');if(!panel)return;
  if(!state.messages.length)panel.innerHTML=`<div class="welcome"><div class="assistant-symbol">≋</div><h2>你好，今天想了解什么？</h2><p>你可以询问机组结构、告警核对、巡检交接与发电指标。涉及具体机型时，请补充机型和告警信息。</p></div>`;
  else panel.innerHTML=state.messages.map(m=>`<article class="message ${m.role}"><div class="message-head">${m.role==='user'?'你':'≋ 风知'}${m.mode?` · ${esc(m.mode)}`:''}</div><div class="message-body">${esc(m.text)}</div>${m.result?`<div class="message-actions"><button data-evidence="${m.result.id}">查看来源与链路</button><button data-feedback="${m.result.id}" data-value="useful">有帮助</button><button data-feedback="${m.result.id}" data-value="needs_review">需要复核</button></div>`:''}</article>`).join('');
  panel.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>sendQuestion(b.dataset.question));
  panel.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>renderEvidence(state.messages.find(m=>m.result?.id===b.dataset.evidence).result));
  panel.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=async()=>{try{await api('feedback',{id:b.dataset.feedback,value:b.dataset.value});toast('反馈已记录')}catch(e){toast(e.message,true)}});
  renderEvidence(state.last);panel.scrollTop=panel.scrollHeight;
}
function renderEvidence(result){
  renderMetrics(result);
  const sources=result?.sources||[];$('#sourceCount').textContent=sources.length+' 份';
  $('#sources').innerHTML=sources.length?sources.map((s,i)=>`<button class="source-link" data-source="${i}"><b>[${i+1}] ${esc(s.title)}</b><small>v${s.version} · ${esc(s.farm)}${s.relevance!==undefined?' · 匹配 '+(s.relevance*100).toFixed(1)+'%':''}</small>${s.relevance!==undefined?`<meter min="0" max="1" value="${s.relevance}" aria-label="相关度"></meter>`:''}</button>`).join(''):'<div class="source-empty">提问后，这里显示命中的资料、版本和原文片段。没有依据时不会虚构引用。</div>';
  $$('[data-source]').forEach(b=>b.onclick=()=>{const s=sources[+b.dataset.source];dialog(s.title,`<div class="legend"><span class="badge">v${s.version}</span><span class="badge grey">${esc(s.farm)}</span></div><div class="document-text">${esc(s.excerpt)}</div>`)});
  const steps=result&&!result.metrics?[{step:'旧版问答记录',detail:'原版本未保存经验证的模型概率与检索得分。请重新提问以查看当前计算结果。'}]:result?.trace||[{step:'限定访问范围',detail:'只检索授权风场与角色可见的有效资料'},{step:'检索与组织证据',detail:state.retrieval||'关键词检索'},{step:'引用与归档',detail:'保留来源版本、问答记录与反馈'}];
  $('#trace').innerHTML=steps.map(t=>`<li><b>${esc(t.step)}</b><p>${esc(t.detail)}</p></li>`).join('');
}
function renderHistory(){$('#historyList').innerHTML=state.history.length?state.history.slice(0,6).map((r,i)=>`<button class="history-item" data-history="${i}">${esc(r.question)}<small>${esc(r.created?.slice(0,16).replace('T',' ')||'本次会话')}</small></button>`).join(''):'<p class="form-note">你的问答记录将保存在这里。</p>';$$('[data-history]').forEach(b=>b.onclick=()=>{if(state.busy)return;const r=state.history[+b.dataset.history];state.last=r;state.messages=[{role:'user',text:r.question},{role:'assistant',text:r.answer,result:r}];renderMessages()})}
async function sendQuestion(given){const question=(given??$('#question').value).trim();if(state.busy||question.length<1)return;state.busy=true;$('#sendButton').disabled=true;$('#sendButton').textContent='检索中…';state.messages.push({role:'user',text:question});$('#question').value='';renderMessages();try{const r=await api('chat',{question,farm:state.farm,previous_id:state.last?.id||''});state.last=r;state.messages.push({role:'assistant',text:r.answer,mode:r.mode,result:r});state.history.unshift({...r,created:new Date().toISOString()});renderMessages();renderHistory();return {id:r.id,answer:r.answer,sources:r.sources}}catch(e){state.messages.push({role:'assistant',text:'本次请求未完成：'+e.message+'。你可以重新发送问题。'});renderMessages();toast(e.message,true)}finally{state.busy=false;if($('#sendButton')){$('#sendButton').disabled=false;$('#sendButton').textContent='发送 ↑'}}}
async function renderKnowledge(){
  state.docs=(await api('docs')).items;
  $('#pageContent').innerHTML=`<div class="page">${heading('知识有序，回答有据。','维护适用风场、访问角色与有效版本，让正确的资料进入问答。',level[state.user.role]>=1?'<button class="primary" id="uploadButton">＋ 导入知识</button>':'')}<div class="notice">示例库用于体验检索与权限。导入你的风机手册、巡检制度或工程资料后，审核发布即可进入问答。</div><div class="filters"><input id="docSearch" placeholder="搜索文档标题或正文" aria-label="搜索知识"><select id="docStatus" aria-label="资料状态"><option value="">全部状态</option><option value="published">已发布</option><option value="staged">待审核</option><option value="retired">历史版本</option></select></div><div class="doc-grid" id="docGrid"></div></div>`;
  $('#docGrid').insertAdjacentHTML('beforebegin','<section class="panel" id="knowledgeSettings"></section>');await renderSettingsPanel('#knowledgeSettings');
  $('#docSearch').oninput=paintDocs;$('#docStatus').onchange=paintDocs;if($('#uploadButton'))$('#uploadButton').onclick=()=>ingestDialog();paintDocs();
}
function paintDocs(){const query=$('#docSearch').value.toLowerCase(),status=$('#docStatus').value;const docs=state.docs.filter(d=>(!status||d.status===status)&&(d.title+d.content).toLowerCase().includes(query));$('#docGrid').innerHTML=docs.length?docs.map(d=>`<article class="doc-card"><span class="badge ${d.status==='staged'?'amber':d.status==='retired'?'grey':''}">${statusText[d.status]}${d.valid===false?' · 已过期':''}</span><h3>${esc(d.title)}</h3><p>${esc(d.content)}</p><div class="doc-meta"><span>${esc(d.farm)}</span><span>v${d.version} · ${d.chunk_count||1} 个片段</span></div><div class="doc-meta"><span>${esc(roles[d.min_role])}起可见</span><span>${esc(d.category)}</span></div><div class="card-actions"><button data-doc="${d.id}">查看原文</button>${level[state.user.role]>=1?`<button data-revise="${d.id}">修订</button>`:''}${level[state.user.role]>=2&&d.status!=='published'?`<button data-publish="${d.id}">${d.status==='retired'?'回滚此版':'审核发布'}</button>`:''}</div></article>`).join(''):'<div class="empty">没有符合条件的可访问资料。</div>';
  $$('[data-doc]').forEach(b=>b.onclick=()=>{const d=state.docs.find(d=>d.id===b.dataset.doc);dialog(d.title,`<div class="legend"><span class="badge">${statusText[d.status]} · v${d.version}</span><span class="badge grey">${esc(d.farm)} · ${roles[d.min_role]}起可见</span></div><div class="document-text">${esc(d.content)}</div>`)});
  $$('[data-revise]').forEach(b=>b.onclick=()=>ingestDialog(state.docs.find(d=>d.id===b.dataset.revise)));
  $$('[data-publish]').forEach(b=>b.onclick=()=>publishDialog(state.docs.find(d=>d.id===b.dataset.publish)));
}
function ingestDialog(doc){dialog(doc?'修订知识 · 新候选版本':'导入知识',`<form id="ingestForm"><p class="form-note">支持 UTF-8 TXT / Markdown 文件，或直接粘贴正文。候选资料通过审核发布后才参与问答。</p><label>选择文本文件<input id="fileInput" type="file" accept=".txt,.md,text/plain,text/markdown"></label><label>资料标题<input name="title" value="${esc(doc?.title||'')}" minlength="2" maxlength="100" required></label><div class="form-row"><label>风场范围<select name="farm">${['公共',...state.user.farms].map(f=>`<option ${doc?.farm===f?'selected':''}>${esc(f)}</option>`).join('')}</select></label><label>最低访问角色<select name="min_role">${Object.entries(roles).filter(([k])=>level[k]<=level[state.user.role]).map(([k,v])=>`<option value="${k}" ${doc?.min_role===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="form-row"><label>资料分类<input name="category" value="${esc(doc?.category||'上传资料')}" required></label><label>有效期截止（可选）<input name="expires" type="date" value="${esc(doc?.expires||'')}"></label></div><label>正文<textarea name="content" rows="9" minlength="30" maxlength="200000" required>${esc(doc?.content||'')}</textarea></label><div class="form-actions"><button class="primary" type="submit">校验并建立候选版本</button></div></form>`);
  $('#fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>800000)return toast('文件不能超过 800 KB',true);if(!/\.(md|txt)$/i.test(file.name))return toast('请选择 TXT 或 Markdown 文件',true);try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());$('#ingestForm [name="content"]').value=text;if(!$('#ingestForm [name="title"]').value)$('#ingestForm [name="title"]').value=file.name.replace(/\.[^.]+$/,'')}catch{toast('请使用 UTF-8 编码的文本文件',true)}};
  $('#ingestForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));if(doc)body.series=doc.series;const r=await api('ingest',body);$('#dialog').close();toast(`候选版本已建立，共 ${r.chunks} 个片段`);await renderKnowledge()}catch(e){toast(e.message,true)}finally{button.disabled=false}};
}
function publishDialog(doc){dialog(doc.status==='retired'?'回滚知识版本':'审核并发布',`<p><b>${esc(doc.title)} · v${doc.version}</b></p><p class="form-note">请核对正文、适用范围与来源。确认后，该版本替换同一资料的当前版本；历史引用快照仍保留。</p><div class="legend"><span class="badge">${esc(doc.farm)}</span><span class="badge grey">${roles[doc.min_role]}起可见</span></div><div class="document-text">${esc(doc.content)}</div><div class="form-actions"><button id="confirmPublish" class="primary">${doc.status==='retired'?'确认回滚':'确认发布'}</button></div>`);$('#confirmPublish').onclick=async e=>{e.target.disabled=true;try{await api('publish',{id:doc.id});$('#dialog').close();toast('生效版本已更新');await renderKnowledge()}catch(err){toast(err.message,true);e.target.disabled=false}}}
const percent=v=>v===null||v===undefined?'—':(v*100).toFixed(1)+'%';
function renderMetrics(result){
  if(!$('#metricsSummary'))return;
  const m=result?.metrics,r=m?.retrieval;
  if(!m){$('#metricsSummary').innerHTML='<p class="form-note">发送问题后显示意图类别、实际得分、耗时与本次阈值快照。未加载 BERT 时不显示模型概率。</p>';$('#metricsDetails').hidden=true;return}
  const labels={greeting:'问候',thanks:'致谢',goodbye:'告别',knowledge_search:'知识咨询',out_of_scope:'业务范围外',permission_denied:'权限越界',prompt_boundary:'指令越界',control_action:'控制操作',realtime_status:'实时查询'};
  $('#metricsSummary').innerHTML=`<div class="metric-grid"><div><span>处理路径</span><b>${esc(result.mode||'历史记录')}</b><small>${esc(labels[m.intent?.label]||m.intent?.label||'')}</small></div><div><span>意图判断来源</span><b>${esc(m.intent?.engine||'未记录')}</b><small>${m.intent?.confidence==null?'BERT 未输出概率':percent(m.intent.confidence)+' / 门槛 '+percent(m.thresholds.confidence_threshold)}</small></div><div><span>${r?'引用 / 可见资料':'FAQ 匹配得分'}</span><b>${r?r.selected_docs+' / '+r.eligible_docs:percent(m.faq?.score)}</b><small>${r?'当前授权范围；不是召回率或正确率':m.faq?'门槛 '+percent(m.faq.threshold):'本分支不执行 FAQ 和文档检索'}</small></div><div><span>处理耗时</span><b>${Number(m.elapsed_ms).toFixed(2)} ms</b><small>本次实际计时</small></div></div>${r?`<p class="metric-note">${esc(r.method)}；${r.eligible_chunks} 个可见片段，${r.candidate_chunks} 个通过召回门槛。BM25 归一化门槛 ${percent(m.thresholds.bm25_threshold)}，综合相关度门槛 ${percent(m.thresholds.rerank_threshold)}。</p>`:''}${m.intent?.warning?`<p class="metric-note">${esc(m.intent.warning)}</p>`:''}`;
  $('#metricsDetails').hidden=!r;
  if(r){$('#metricsDetails').open=true;$('#metricTable').innerHTML=`<table><thead><tr><th>候选资料</th><th>BM25 原始分</th><th>归一化分</th><th>综合相关度</th><th>结果</th></tr></thead><tbody>${r.candidates.map(c=>`<tr><td>${esc(c.title)}<small>v${c.version} · ${esc(c.farm)}</small></td><td>${Number(c.raw_score).toFixed(3)}</td><td>${percent(c.bm25_normalized)}</td><td><meter min="0" max="1" value="${c.relevance}"></meter> ${percent(c.relevance)}</td><td class="${c.selected?'grant':'denied'}">${esc(c.reason)}</td></tr>`).join('')||'<tr><td colspan="5">当前授权范围内没有有效知识片段</td></tr>'}</tbody></table><p class="form-note">归一化 = BM25 ÷ (BM25 + 6)。综合相关度 = 65% × 召回分 + 35% × 查询词覆盖比例；配置向量时召回分取归一化分与语义分中的较大值。分数用于匹配排序，不代表答案正确概率，也未冒充 CrossEncoder 模型输出。</p>`}
}
async function renderSettingsPanel(selector){
 const container=$(selector);if(!container)return;
 const data=await api('settings'),labels={faq_threshold:['FAQ 匹配门槛','标准问法 / 已维护同义问法的实际相似分'],bm25_threshold:['BM25 召回门槛','原始分归一化后的最低分'],rerank_threshold:['综合相关度门槛','召回分与查询词覆盖的综合得分'],confidence_threshold:['BERT 意图门槛','模型加载后：低于门槛先澄清']};
 container.innerHTML=`<div class="panel-title"><h2>检索与意图阈值</h2><span class="badge grey">${data.editable?'管理员可编辑':'只读'}</span></div><div class="threshold-cards">${Object.entries(data.items).map(([k,v])=>`<div class="threshold-card"><b>${labels[k][0]}</b><strong>${percent(v)}</strong><span>${labels[k][1]}</span></div>`).join('')}</div><p class="form-note">${window.WIND_DEMO?'演示配置保存在当前浏览器，影响下一次本地问答。':'配置保存在数据库，重启后保留，下一次问答使用新配置。'} BERT 未加载时采用规则分流，其概率门槛暂不参与判断。</p>${data.editable?'<button class="edit-settings">编辑阈值</button>':''}`;
 if(data.editable)container.querySelector('.edit-settings').onclick=()=>{dialog('调整下一次问答的阈值',`<form id="realSettingsForm">${Object.entries(data.items).map(([k,v])=>`<label>${labels[k][0]}<input name="${k}" type="number" min="0" max="1" step="0.01" value="${v}" required></label>`).join('')}<p class="form-note">输入 0–1。提高门槛会筛掉更多候选；没有资料达标时进入澄清，不强行返回答案。历史记录保留当时的配置。</p><div class="form-actions"><button class="primary">保存配置</button></div></form>`);$('#realSettingsForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('settings',Object.fromEntries(new FormData(e.target)));$('#dialog').close();toast('已保存，下一次问答生效');await renderSettingsPanel(selector)}catch(err){toast(err.message,true);button.disabled=false}}}
}
async function renderPipeline(){
  const online=[["Stage 0 · 查询上下文","校验角色与风场，关联本人会话，限定有效知识版本。"],["Stage 1 · 快速路由","边界请求直接响应；标准 FAQ 精确命中直出，其余进入检索准备。"],["Stage 2 · 检索准备","关联追问上下文；BERT 服务可用时判断意图，否则规则分流。低置信度先澄清。"],["Stage 3 · FAQ 检索","复用授权 FAQ 候选，计算问法相似度；达到阈值返回标准答案，不满足则回退文档检索。"],["Stage 4 · 文档检索与排序","BM25 召回；配置向量服务时融合向量结果。按真实相关度和阈值筛选。"],["Stage 5 · 证据准备","去重、选取片段，保留来源、版本、引用编号；无证据则澄清。"],["Stage 6 · 回答与核验","配置 LLM 后基于证据生成并检查引用；未配置或失败时返回原文摘录。"],["Stage 7 · 完成与归档","保存回答、来源、Trace、阈值快照及本人历史，接收反馈。"]];
  const offline=[["01 · 资料与候选版本","上传 TXT / Markdown 或粘贴正文，修订建立独立候选版本。"],["02 · 加载与标准化","检查标题、正文、角色、风场与有效期，保留来源标识。"],["03 · 文档切分","生成 600 字片段，重叠 80 字；维护文档与片段的对应关系。"],["04 · 索引准备","保存文本供 BM25 检索；向量服务启用后首次查询编码并缓存。"],["05 · 候选资料检查","核对内容、适用范围与片段。候选知识不参与在线回答。"],["06 · 发布判断","知识管理员审核；未通过则继续修订，当前已发布版本继续服务。"],["07 · 激活有效版本","通过后事务切换当前版本，同一资料仅一个版本生效。"],["08 · 版本追溯与回滚","保留历史资料与引用快照，需要时回滚到有效历史版本。"]];
  $('#pageContent').innerHTML=`<div class="page">${heading('在线有依据，离线有治理。','沿用在线检索与离线发布双链路，加入风场和资料级别的访问过滤。')}<div class="tabs"><button class="active" id="onlineTab">在线问答链路</button><button id="offlineTab">离线知识链路</button></div><div id="routeDiagram" class="route-diagram"></div><div class="flow-board" id="flowBoard"></div><p class="flow-caption" id="flowCaption"></p><section class="panel threshold-panel" id="thresholdPanel"><div class="panel-title"><h2>检索与判断阈值</h2><span class="badge grey">${state.user.role==='admin'?'管理员可编辑':'只读配置'}</span></div><div id="thresholdCards" class="threshold-cards"></div></section><div class="split-panels"><section class="panel"><h3>分支与异常处理</h3><ul class="branch-list"><li>实时机组数据 → 提示从授权 SCADA 查询。</li><li>控制操作 / 保护绕过 → 转授权人员核实。</li><li>无有效证据 → 补问机型或建议补充资料。</li><li>模型服务失败 → 返回已检索的原文摘录。</li></ul></section><section class="panel"><h3>版本与权限边界</h3><ul class="branch-list"><li>检索前按角色、风场和有效期过滤。</li><li>候选版本不参与问答。</li><li>同一资料仅一个已发布版本。</li><li>个人问答历史和反馈按账号隔离。</li></ul></section></div></div>`;
  await renderSettingsPanel('#thresholdPanel');
  function paint(kind){$('#routeDiagram').innerHTML=kind==='online'?'<div class="route-entry">Stage 0 上下文 → Stage 1 快速路由：规则直出 / FAQ 精确命中 / retrieval</div><div class="route-branches four"><article><b>问候 / 致谢 / 告别</b><p>完整问句命中社交意图</p><strong>固定回复直出，无知识引用</strong><p>↓ 记录分流结果</p></article><article><b>Stage 1 · FAQ 精确命中</b><p>校验有效来源与问法条件</p><strong>标准答案直出 + 引用</strong><p>↓ 问答归档与反馈</p></article><article><b>FAQ 未命中 / 不适用</b><p>Stage 2 意图与检索准备 → Stage 3 FAQ 阈值匹配<br>未达阈值 → Stage 4 文档召回与排序</p><strong>Stage 5 证据整理 → Stage 6 生成或摘录 → 校验</strong><p>↓ 问答归档与反馈</p></article><article><b>实时 / 控制类请求</b><p>在任务分流阶段优先识别</p><strong>说明未接入或转授权人员核实</strong><p>↓ 处理结果归档</p></article></div>':'<div class="route-entry">资料接入 → 元数据检查 → 候选版本 → 切分与索引 → 审核发布</div><div class="route-branches"><article><b>检查通过</b><p>切换生效版本 → 在线检索可用</p></article><article><b>检查失败</b><p>修订后重新导入；当前版本继续服务</p></article><article><b>来源更新与 FAQ</b><p>旧来源对应 FAQ 停止直出；重新审核标准答案后维护配置</p></article></div>';const steps=kind==='online'?online:offline;$('#flowBoard').innerHTML=steps.map(([a,b],i)=>`<article class="flow-step ${[0,7].includes(i)?'accent':''}"><span class="number">${String(i+1).padStart(2,'0')} / ${kind==='online'?'ONLINE':'OFFLINE'}</span><h3>${a}</h3><p>${b}</p></article>`).join('');$('#flowCaption').textContent=kind==='online'?'快速分支在 Stage 1 结束检索并统一归档；检索分支按 Stage 2–7 执行。FAQ 精确命中不调用 BERT，FAQ 相似匹配失败才查询文档。当前传输采用 HTTP；BM25 和可选向量服务负责检索，未加载的模型不会显示模拟概率。':'资料按 01 → 08 顺序处理。校验失败先修订再导入；发布异常时可选择历史有效版本回滚，再修订进入下一轮候选发布。';$('#onlineTab').classList.toggle('active',kind==='online');$('#offlineTab').classList.toggle('active',kind==='offline')}
  $('#onlineTab').onclick=()=>paint('online');$('#offlineTab').onclick=()=>paint('offline');paint('online');
}
async function renderAccess(){
  const capabilities=[['项目概览与账号权限管理（运行版）',0,0,0,1],['链路与版本页面（运行版）',0,1,1,1],['知识问答与本人记录',1,1,1,1],['授权风场内的普通资料',1,1,1,1],['工程资料与候选修订',0,1,1,1],['知识审核 / 发布 / 回滚',0,0,1,1],['知识治理资料与审计',0,0,1,1],['创建账号与分配风场',0,0,0,1],['查看问答阈值配置',1,1,1,1],['修改问答阈值配置',0,0,0,1]];
  capabilities.forEach(row=>row.splice(1,0,['知识问答与本人记录','授权风场内的普通资料','查看问答阈值配置'].includes(row[0])?1:0));
  capabilities.unshift(['运行数据与报表查看',1,1,1,1,1],['执行预测 / 检测 / 运维处理',0,1,1,0,1],['导入与清洗 / 设备维护 / 用户管理',0,0,0,0,1]);
  $('#pageContent').innerHTML=`<div class="page">${heading('按职责协作，按范围访问。','角色决定可执行的操作，风场范围决定可访问的数据。',state.user.role==='admin'?'<button class="primary" id="addUser">＋ 创建账号</button>':'')}<div class="notice">当前身份：${roles[state.user.role]} · 授权风场：${state.user.farms.map(esc).join('、')}。${window.WIND_DEMO?'演示版无需登录，角色切换用于展示权限差异；实际权限由运行版后端执行。':'每次检索、导入、发布和账号操作均由后端校验，隐藏按钮不能替代权限检查。'}</div><section class="panel table-wrap"><table><thead><tr><th>能力 / 操作</th>${Object.values(roles).map(r=>`<th>${r}</th>`).join('')}</tr></thead><tbody>${capabilities.map(([name,...grants])=>`<tr><td>${name}</td>${grants.map(g=>`<td class="${g?'grant':'denied'}">${g?'允许':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></section><section class="panel"><h3>资料访问规则</h3><p class="form-note">只有同时满足“最低访问角色”和“授权风场”的资料才能被检索。公共资料不限制风场，但仍遵守角色级别。运维人员默认仅获北岭风场访问权，其余初始账号获两个示例风场访问权。</p></section><div id="userTable"></div></div>`;
  if(state.user.role==='admin'){$('#addUser').onclick=userDialog;const users=(await api('users')).items;$('#userTable').innerHTML=`<section class="panel"><div class="panel-title"><h2>账号与授权</h2><span class="badge grey">${users.length} 个账号</span></div><div class="table-wrap"><table><thead><tr><th>账号</th><th>姓名</th><th>角色</th><th>风场范围</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.name)}</td><td>${roles[u.role]}</td><td>${u.farms.map(esc).join('、')}</td></tr>`).join('')}</tbody></table></div></section>`}
}
function userDialog(){dialog('创建账号与分配权限',`<form id="userForm"><div class="form-row"><label>账号<input name="username" pattern="[A-Za-z0-9_]{3,30}" required placeholder="3–30 位字母、数字或下划线"></label><label>显示姓名<input name="name" required maxlength="40"></label></div><label>初始密码<input name="password" type="password" minlength="10" required autocomplete="new-password"></label><label>角色<select name="role">${Object.entries(roles).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>授权风场</label><div class="checks">${['北岭风场','海岬风场'].map(f=>`<label><input type="checkbox" name="farms" value="${f}">${f}</label>`).join('')}</div><div class="form-actions"><button class="primary" type="submit">创建账号</button></div></form>`);$('#userForm').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target),body=Object.fromEntries(data);body.farms=data.getAll('farms');try{await api('users',body);$('#dialog').close();toast('账号已创建');await renderAccess()}catch(e){toast(e.message,true)}}}
async function renderAudit(){const items=(await api('audit')).items;$('#pageContent').innerHTML=`<div class="page">${heading('关键操作，留痕可查。','记录登录、知识修改、版本发布与问答反馈，显示最近 100 条。')}<section class="panel table-wrap"><table><thead><tr><th>时间（UTC）</th><th>账号</th><th>操作</th><th>关联记录</th></tr></thead><tbody>${items.map(r=>`<tr><td>${esc(r.created.replace('T',' ').slice(0,19))}</td><td>${esc(r.actor)}</td><td>${esc(r.action)}</td><td>${esc(r.target||'—')}</td></tr>`).join('')||'<tr><td colspan="4">暂无操作记录</td></tr>'}</tbody></table></section></div>`}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');if(button)button.disabled=true;$('#loginError').textContent='';try{await api('login',Object.fromEntries(new FormData(e.target)));e.target.reset();state.messages=[];state.last=null;state.farm='';await boot()}catch(err){$('#loginError').textContent=err.message}finally{if(button)button.disabled=false}};
$$('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
$('#logoutButton').onclick=async()=>{if(state.busy||state.navigating)return toast('操作处理中，请稍候');try{await api('logout',{});state.messages=[];state.last=null;state.farm='';if(window.WIND_DEMO){window.demoSession='operator';await boot()}else showLogin()}catch(e){toast(e.message,true)}};
$('#accountButton').onclick=()=>{if(window.WIND_DEMO)return toast('演示版无需登录，可使用顶部“切换演示身份”切换身份；密码管理由运行版提供');dialog('个人账户',`<p class="form-note">${esc(state.user.name)} · ${roles[state.user.role]}</p><form id="passwordForm"><label>原密码<input type="password" name="old" autocomplete="current-password" required></label><label>新密码<input type="password" name="new" minlength="10" autocomplete="new-password" required></label><div class="form-actions"><button class="primary">更新密码</button></div></form>`);$('#passwordForm').onsubmit=async e=>{e.preventDefault();try{await api('password',Object.fromEntries(new FormData(e.target)));$('#dialog').close();toast('密码已更新，其他会话已退出')}catch(e){toast(e.message,true)}}};
$('#demoRole').onchange=async e=>{if(state.busy){e.target.value=state.user.role;return toast('正在回答，请稍候')}window.demoSession=e.target.value;state.messages=[];state.last=null;state.farm='';await boot()};
try{document.modelContext?.registerTool({name:'ask_wind_knowledge',description:'向风知提交一个风电知识问题，保存问答并更新界面。',inputSchema:{type:'object',properties:{question:{type:'string',minLength:2,maxLength:2000}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.question!=='string'||input.question.length<2||input.question.length>2000)throw Error('问题需为 2–2000 字符');if(!state.user||state.busy)throw Error('请先登录并等待当前问答完成');await navigate('chat');return await sendQuestion(input.question)}})}catch{}
function setupLoginExtras(){const toggle=$('#togglePassword');if(toggle)toggle.onclick=()=>{const field=$('#loginForm [name=password]');field.type=field.type==='password'?'text':'password';toggle.textContent=field.type==='password'?'显示密码':'隐藏密码'};const credentials={admin:'admin123',operator:'operator123',user:'user123'};$$('[data-demo-account]').forEach(button=>button.onclick=()=>{const username=button.dataset.demoAccount;$('#loginForm [name=username]').value=username;$('#loginForm [name=password]').value=credentials[username]||'';$('#loginError').textContent='';$('#loginForm [name=password]').focus()});const tick=()=>{if($('#currentClock'))$('#currentClock').textContent=new Date().toLocaleString('zh-CN')};tick();setInterval(tick,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupLoginExtras);else setupLoginExtras();
boot();
