'use strict';
window.Ops={
 titles:{dashboard:'首页驾驶舱',farms:'风场管理',turbines:'风机信息',data:'数据查询',imports:'数据导入与处理',analysis:'运行数据分析',prediction:'发电功率预测',monitoring:'设备状态',alerts:'异常检测与告警',maintenance:'运维中心',reports:'报表中心',users:'用户管理',logs:'操作日志',preferences:'系统设置'},
 meta:null,
 async get(path,body){return api('ops/'+path,body)},
 writable(){return ['admin','operator','engineer'].includes(state.user.role)},
 async render(page){this.meta=await this.get('meta');$('#pageContent').innerHTML=`<div class="page ops-page">${heading(this.titles[page],'风知 · 风电智能运维与数据分析平台')}<div id="opsBody" aria-live="polite"><p class="loading">正在读取数据…</p></div></div>`;await this[page]();},
 num(v){return v===null||v===undefined?'—':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):esc(v)},
 table(rows,columns,actions){return `<div class="table-wrap"><table><thead><tr>${columns.map(([k,t])=>`<th>${esc(t)}</th>`).join('')}${actions?'<th>操作</th>':''}</tr></thead><tbody>${rows.map((r,i)=>`<tr>${columns.map(([k])=>`<td>${this.num(r[k])}</td>`).join('')}${actions?`<td class="row-actions">${actions(r,i)}</td>`:''}</tr>`).join('')||`<tr><td colspan="${columns.length+!!actions}" class="empty">暂无符合条件的数据</td></tr>`}</tbody></table></div>`},
 btn(text,cls=''){return `<button class="${cls}" type="submit">${text}</button>`},
 select(name,label,items,all=true){return `<label>${label}<select name="${name}">${all?'<option value="">全部</option>':''}${items.map(x=>`<option value="${esc(x.id??x)}">${esc(x.name??x)}</option>`).join('')}</select></label>`},
 filters(extra='',single=false){return `<form id="opsFilter" class="ops-filters">${this.select('farm','风场',this.meta.farms)}${this.select('turbine','风机',this.meta.turbines,single?false:true)}<label>起始日期<input type="date" name="start"></label><label>结束日期<input type="date" name="end"></label>${extra}${this.btn('查询 / 更新','primary')}</form>`},
 async action(button,fn){if(button)button.disabled=true;try{return await fn()}catch(e){toast(e.message,true)}finally{if(button)button.disabled=false}},
 bindForm(id,fn){$(id).onsubmit=e=>{e.preventDefault();this.action(e.submitter,()=>fn(Object.fromEntries(new FormData(e.target))))}},
 query(data){return new URLSearchParams(Object.entries(data).filter(([k,v])=>v!==''&&v!==undefined)).toString()},
 chart(rows,key,title,{scatter=false,series=null}={}){
  const data=rows.filter(r=>Number.isFinite(r[key])&&(!scatter||Number.isFinite(r.wind_speed)));if(!data.length)return `<section class="chart-card"><h3>${title}</h3><p class="empty">暂无有效数据</p></section>`;
  const w=640,h=230,p=45,min=0,max=Math.max(1,...data.flatMap(r=>[r[key],...(series?[r[series]||0]:[])]))*1.08,xmax=scatter?Math.max(1,...data.map(r=>r.wind_speed))*1.05:Math.max(1,data.length-1),x=(r,i)=>p+(scatter?r.wind_speed:i)/xmax*(w-p-15),y=v=>h-35-(v-min)/(max-min)*(h-55);
  const path=field=>data.map((r,i)=>`${i?'L':'M'}${x(r,i).toFixed(1)},${y(r[field]||0).toFixed(1)}`).join(' ');
  return `<section class="chart-card"><h3>${title}</h3><svg class="data-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}">${[0,.25,.5,.75,1].map(f=>`<path d="M${p} ${y(max*f)}H${w-15}" stroke="#dde9ef"/><text x="${p-5}" y="${y(max*f)+4}" text-anchor="end">${Math.round(max*f)}</text>`).join('')}${scatter?data.map((r,i)=>`<circle cx="${x(r,i)}" cy="${y(r[key])}" r="3" fill="#058d93" opacity=".6"><title>风速 ${r.wind_speed} m/s / 功率 ${r[key]} kW</title></circle>`).join(''):`<path d="${path(key)}" fill="none" stroke="#07858a" stroke-width="2.5"/>${series?`<path d="${path(series)}" fill="none" stroke="#dc9440" stroke-width="2" stroke-dasharray="6 4"/>`:''}` }<text x="${p}" y="${h-10}">${esc(scatter?'0 m/s':data[0].time?.slice(5,16)||'开始')}</text><text x="${w-15}" y="${h-10}" text-anchor="end">${esc(scatter?xmax.toFixed(1)+' m/s':data.at(-1).time?.slice(5,16)||'结束')}</text></svg>${series?'<p class="chart-legend">青色：实际值　橙色虚线：预测值</p>':''}</section>`
 },
 bars(obj,title){const entries=Array.isArray(obj)?obj.map(r=>[r.name,r.value]):Object.entries(obj);const max=Math.max(1,...entries.map(x=>x[1]));return `<section class="chart-card"><h3>${title}</h3>${entries.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><meter min="0" max="${max}" value="${v}"></meter><b>${this.num(v)}</b></div>`).join('')}</section>`},
 pager(result,go){const area=$('#pager');if(!area)return;area.innerHTML=`<span>共 ${result.total} 条 · 第 ${result.page} / ${Math.max(1,Math.ceil(result.total/result.size))} 页</span><button id="prevData" ${result.page<=1?'disabled':''}>上一页</button><button id="nextData" ${result.page*result.size>=result.total?'disabled':''}>下一页</button>`;$('#prevData').onclick=()=>this.action($('#prevData'),()=>go(result.page-1));$('#nextData').onclick=()=>this.action($('#nextData'),()=>go(result.page+1))},
 async dashboard(){const d=await this.get('dashboard');$('#opsBody').innerHTML=`<div class="ops-source">${esc(d.source)} · 数据截至 ${esc(d.as_of.replace('T',' '))}<button id="dashRefresh">刷新数据</button></div><div class="kpi-grid">${Object.entries(d.kpis).map(([k,v])=>`<article><span>${k}</span><strong>${this.num(v)}</strong></article>`).join('')}</div><div class="chart-grid">${this.chart(d.trend,'power','今日总功率 / kW')}${this.chart(d.trend,'wind_speed','今日平均风速 / m/s')}${this.chart(d.scatter,'power','风速—功率分布',{scatter:true})}${this.bars(d.states,'风机状态分布')}${this.bars(d.levels,'告警级别分布')}${this.bars(d.ranking,'各风机累计发电量 / kWh')}</div><section class="panel"><h3>最近告警</h3>${this.table(d.alerts,[['turbine_id','风机'],['metric','指标'],['level','等级'],['status','状态'],['time','时间']])}</section><section class="panel"><h3>最近运维</h3>${this.table(d.maintenance,[['turbine_id','风机'],['kind','类型'],['problem','内容'],['handler','处理人']])}</section>`;$('#dashRefresh').onclick=()=>this.action($('#dashRefresh'),()=>this.dashboard())},
 async farms(){const d=await this.get('farms');$('#opsBody').innerHTML=`${state.user.role==='admin'?'<button id="addFarm" class="primary">＋ 新增风场</button>':''}<section class="panel">${this.table(d.items,[['name','名称'],['region','地区'],['capacity','装机容量 kW'],['turbine_count','风机数'],['manager','负责人'],['commissioned','投运日期'],['status','状态']],state.user.role==='admin'?(r,i)=>`<button data-edit="${i}">编辑</button><button data-delete="${i}">删除</button>`:null)}</section>`;if($('#addFarm'))$('#addFarm').onclick=()=>this.editFarm();$$('[data-edit]').forEach(el=>el.onclick=()=>this.editFarm(d.items[+el.dataset.edit]));$$('[data-delete]').forEach(el=>el.onclick=()=>this.remove('farms',d.items[+el.dataset.delete],()=>this.farms()))},
 input(key,label,value='',type='text',required=true){return `<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`},
 formDialog(title,html,save){dialog(title,`<form id="opsEdit">${html}<div class="form-actions"><button type="submit" class="primary">保存</button></div></form>`);this.bindForm('#opsEdit',async body=>{await save(body);$('#dialog').close();toast('已保存')})},
 remove(module,r,reload){dialog('确认删除',`<p>确定删除 ${esc(r.name||r.username||r.id)}？</p><p>存在关联运行记录的设备会受到保护。</p><button id="confirmRemove" class="primary">确认删除</button>`);$('#confirmRemove').onclick=()=>this.action($('#confirmRemove'),async()=>{await this.get(module,{id:r.id,action:'delete'});$('#dialog').close();toast('已删除');await reload()})},
 editFarm(r={}){this.formDialog(r.id?'编辑风场':'新增风场',`<div class="form-row">${this.input('name','风场名称',r.name)}${this.input('region','地区',r.region)}${this.input('capacity','装机容量 kW',r.capacity||15000,'number')}${this.input('manager','负责人',r.manager)}${this.input('commissioned','投运日期',r.commissioned||'2023-06-01','date')}${this.input('status','状态',r.status||'运行')}</div>${this.input('notes','备注',r.notes||'','text',false)}`,async b=>{await this.get('farms',{...b,id:r.id});await this.farms()})},
 async turbines(){let query={};$('#opsBody').innerHTML=`<form id="machineFilter" class="ops-filters">${this.select('farm','风场',this.meta.farms)}${this.input('q','编号或名称','','text',false)}${this.select('status','状态',['正常','注意','告警','故障','停机'])}${this.btn('查询','primary')}</form>${state.user.role==='admin'?'<button id="addMachine" class="primary">＋ 新增风机</button>':''}<section class="panel" id="machineRows"></section><div class="pager" id="pager"></div>`;
  const load=async p=>{const d=await this.get('turbines?'+this.query({...query,page:p}));$('#machineRows').innerHTML=this.table(d.items.map(r=>({...r,current_status:r.current?.status||r.status,wind_speed:r.current?.wind_speed,power:r.current?.power,temperature:r.current?.temperature,rpm:r.current?.rpm})),[['id','编号'],['name','名称'],['farm_name','风场'],['model','型号'],['rated_power','额定 kW'],['current_status','状态'],['wind_speed','风速'],['power','功率']],(r,i)=>`<button data-detail="${i}">详情</button>${state.user.role==='admin'?`<button data-edit="${i}">编辑</button><button data-delete="${i}">删除</button>`:''}`);$$('[data-detail]').forEach(b=>b.onclick=()=>this.action(b,()=>this.machineDetail(d.items[+b.dataset.detail])));$$('[data-edit]').forEach(b=>b.onclick=()=>this.editMachine(d.items[+b.dataset.edit]));$$('[data-delete]').forEach(b=>b.onclick=()=>this.remove('turbines',d.items[+b.dataset.delete],()=>load(1)));this.pager(d,load)};
  this.bindForm('#machineFilter',async b=>{query=b;await load(1)});if($('#addMachine'))$('#addMachine').onclick=()=>this.editMachine();await load(1)
 },
 editMachine(r={}){this.formDialog('风机设备信息',`<div class="form-row">${this.input('id','风机编号',r.id)}${this.input('name','风机名称',r.name)}${this.select('farm_id','风场',this.meta.farms,false)}${this.input('model','型号',r.model||'W-3000')}${this.input('rated_power','额定功率 kW',r.rated_power||3000,'number')}${this.input('location','经纬度 / 位置',r.location)}${this.input('commissioned','投运日期',r.commissioned||'2023-06-01','date')}${this.select('status','设备状态',['正常','注意','告警','故障','停机'],false)}</div>`,async b=>{await this.get('turbines',b);await this.turbines()});if(r.id){$('#opsEdit [name=id]').readOnly=true;$('#opsEdit [name=farm_id]').value=r.farm_id;$('#opsEdit [name=status]').value=r.status}},
 async machineDetail(r){const [a,alerts,work]=await Promise.all([this.get('analysis?turbine='+encodeURIComponent(r.id)),this.get('alerts?size=100'),this.get('maintenance?size=100')]);dialog(r.id+' · '+r.name,`<p>${esc(r.farm_name)} · ${esc(r.model)} · ${r.rated_power} kW</p><p>位置 ${esc(r.location)} · 投运 ${esc(r.commissioned)} · 状态 ${esc(r.current?.status||r.status)}</p><p>温度 ${this.num(r.current?.temperature)} ℃ · 转速 ${this.num(r.current?.rpm)} rpm</p>${this.chart(a.items.slice(-48),'power','近期功率 / kW')}${this.chart(a.items.slice(-48),'wind_speed','近期风速 / m/s')}<h3>近期运行数据</h3>${this.table(a.items.slice(-6),[['time','时间'],['power','功率'],['temperature','温度'],['rpm','转速']])}<h3>历史告警</h3>${this.table(alerts.items.filter(x=>x.turbine_id===r.id),[['time','时间'],['metric','类型'],['status','状态']])}<h3>运维记录</h3>${this.table(work.items.filter(x=>x.turbine_id===r.id),[['kind','类型'],['problem','问题'],['result','结果']])}`)},
 async data(){let query={};$('#opsBody').innerHTML=this.filters(`${this.select('status','状态',['正常','注意','告警','故障','停机'])}${this.input('q','关键词','','text',false)}`)+'<section class="panel" id="dataRows"></section><div class="pager" id="pager"></div>';const load=async p=>{const d=await this.get('data?'+this.query({...query,page:p}));$('#dataRows').innerHTML=this.table(d.items,[['time','时间'],['turbine_id','风机'],['wind_speed','风速 m/s'],['power','功率 kW'],['temperature','温度 ℃'],['rpm','转速 rpm'],['status','状态']]);this.pager(d,load)};this.bindForm('#opsFilter',async b=>{query=b;await load(1)});await load(1)},
 download(name,content,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff'+content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},
 async imports(){const d=await this.get('batches');$('#opsBody').innerHTML=`<section class="panel"><h3>导入 → 预览 → 确认 → 清洗 → 分析</h3><p>CSV 必需列：turbine_id、time、wind_speed、power、temperature、rpm。先保存原始批次，再将清洗结果写入运行数据。</p><div class="ops-filters"><label>选择 CSV<input type="file" id="csvFile" accept=".csv,text/csv"></label><button id="sampleCsv">下载 Demo CSV</button></div><div id="preview"></div></section><section class="panel"><h3>导入批次与处理记录</h3>${this.table(d.items.map(r=>({...r,rows:r.report.before?.rows??r.report.rows})),[['name','文件'],['rows','原始行数'],['status','状态'],['created','导入时间']],(r,i)=>`<button data-batch="${i}">${r.status==='预览'?'确认导入':r.status==='已处理'?'查看处理结果':'执行清洗'}</button>`)}</section><section id="qualityResults"></section>`;
 $('#sampleCsv').onclick=()=>this.action($('#sampleCsv'),async()=>{const r=await this.get('demo-csv');this.download(r.name,r.content)});
 $('#csvFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;await this.action(e.target,async()=>{if(file.size>850000)throw Error('文件应小于 850 KB');const r=await this.get('import/preview',{name:file.name,content:await file.text()});$('#preview').innerHTML=`<h3>预览 ${r.report.rows} 行</h3>${this.qualitySummary(r.report)}${this.table(r.preview,[['turbine_id','风机'],['time','时间'],['wind_speed','风速'],['power','功率'],['temperature','温度'],['rpm','转速']])}<button class="primary" id="confirmImport">确认导入原始批次</button>`;$('#confirmImport').onclick=()=>this.action($('#confirmImport'),async()=>{await this.get('import/confirm',{id:r.id});toast('原始数据已保存，可以执行清洗');await this.imports()})})};
 $$('[data-batch]').forEach(el=>el.onclick=()=>this.action(el,async()=>{const r=d.items[+el.dataset.batch];if(r.status==='预览'){await this.get('import/confirm',{id:r.id});await this.imports()}else if(r.status==='已处理')this.qualityResult(r.report);else{const result=await this.get('data/clean',{id:r.id});await this.imports();this.qualityResult(result);toast('清洗完成，运行数据已更新')}}))
 },
 qualitySummary(r){const labels={rows:'数据行',missing:'缺失字段',outliers:'异常字段',duplicates:'重复行',types:'类型错误',times:'时间错误'};return `<div class="quality-grid">${Object.entries(r).filter(([k])=>labels[k]).map(([k,v])=>`<span>${labels[k]}<b>${v}</b></span>`).join('')}</div>`},
 qualityResult(r){$('#qualityResults').innerHTML=`<section class="panel"><h3>处理前</h3>${this.qualitySummary(r.before)}<h3>处理后</h3>${this.qualitySummary(r.after)}<p>${esc(r.policy)}</p><div class="chart-grid"><div><h3>原始预览</h3>${this.table(r.before_preview,[['time','时间'],['wind_speed','风速'],['temperature','温度']])}</div><div><h3>处理后预览</h3>${this.table(r.after_preview,[['time','时间'],['wind_speed','风速'],['temperature','温度']])}</div></div></section>`;$('#qualityResults').scrollIntoView({behavior:'smooth',block:'start'})},
 async analysis(){ $('#opsBody').innerHTML=this.filters(this.select('metric','分析指标',Object.entries(this.meta.metrics).map(([id,v])=>({id,name:v[0]})),false),true)+'<div id="analysisOutput"></div>';const run=async b=>{const d=await this.get('analysis?'+this.query(b));$('#analysisOutput').innerHTML=`<section class="panel"><h3>统计结果 · ${d.total} 条观测 · ${this.num(d.energy)} kWh</h3>${this.table(Object.entries(d.stats).map(([key,v])=>({metric:this.meta.metrics[key][0],...v})),[['metric','指标'],['count','有效数据量'],['mean','平均值'],['min','最小值'],['max','最大值'],['std','标准差']])}</section><div class="chart-grid">${['wind_speed','power','temperature','rpm'].sort((a,c)=>a===b.metric?-1:c===b.metric?1:0).map(k=>this.chart(d.items,k,this.meta.metrics[k][0]+' / '+this.meta.metrics[k][1])).join('')}${this.chart(d.items,'power','风速—功率散点',{scatter:true})}</div>`};this.bindForm('#opsFilter',run);await run({turbine:this.meta.turbines[0]?.id})},
 async prediction(){const d=await this.get('prediction');$('#opsBody').innerHTML=(this.writable()?`<form id="predictForm" class="ops-filters">${this.select('turbine','风机',this.meta.turbines,false)}${this.input('start','起始日期','','date',false)}${this.input('end','结束日期','','date',false)}<label>预测步数<input type="number" name="horizon" min="1" max="72" value="12" required></label>${this.btn('开始预测','primary')}</form>`:'<p class="notice">普通用户可查看已生成的预测结果。</p>')+`<section class="panel"><h3>预测记录</h3>${this.table(d.items,[['created','时间'],['turbine_id','风机'],['actor','执行人']],(r,i)=>`<button data-result="${i}">查看结果</button>`)}</section><div id="predictionOutput"></div>`;if($('#predictForm'))this.bindForm('#predictForm',async b=>{const result=await this.get('prediction',b);this.predictionResult(result);toast('预测完成并保存')});$$('[data-result]').forEach(b=>b.onclick=()=>this.predictionResult(d.items[+b.dataset.result].result));if(d.items.length)this.predictionResult(d.items[0].result)},
 predictionResult(r){$('#predictionOutput').innerHTML=`<section class="panel"><h3>运行完成 · ${esc(r.model)}</h3><p>${esc(r.explanation)}</p><p>历史训练段 ${r.train_count} 条 · 留出回测段 ${r.test_count} 条</p><div class="quality-grid">${Object.entries(r.metrics).map(([k,v])=>`<span>${k}<b>${this.num(v)}</b></span>`).join('')}</div></section><div class="chart-grid">${this.chart(r.history,'power','历史功率 / kW')}${this.chart(r.comparison,'actual','回测：实际与预测 / kW',{series:'predicted'})}${this.chart(r.future,'predicted','未来功率预测 / kW')}</div>${this.table(r.future,[['time','预测时刻'],['predicted','预测功率 kW']])}`},
 async monitoring(){const d=await this.get('monitoring');$('#opsBody').innerHTML=`<div class="ops-source">${esc(d.source)} · 刷新于 ${esc(d.refreshed)}<button id="monitorRefresh">刷新快照</button></div><div class="machine-grid">${d.items.map(t=>`<article class="machine-card"><span class="badge ${['故障','告警'].includes(t.current?.status)?'amber':''}">${esc(t.current?.status||t.status)}</span><h2>${esc(t.id)}</h2><p>${esc(t.name)} · ${esc(t.farm_name)}</p><div class="machine-readings">${['wind_speed','power','temperature','rpm'].map(k=>`<div><small>${this.meta.metrics[k][0]}</small><b>${this.num(t.current?.[k])}</b><span>${this.meta.metrics[k][1]}</span></div>`).join('')}</div><small>采样 ${esc(t.current?.time||'暂无数据')}</small></article>`).join('')}</div>`;$('#monitorRefresh').onclick=()=>this.action($('#monitorRefresh'),()=>this.monitoring())},
 async alerts(){let query={};$('#opsBody').innerHTML=`${this.writable()?'<button id="runDetection" class="primary">运行异常检测</button>':''}<p class="notice">按温度、风速、转速与额定功率规则检查授权范围内的数据；重复检测不会重复创建告警。</p><div id="detectionResult"></div><form id="alertFilter" class="ops-filters">${this.select('status','处理状态',['未处理','处理中','已处理'])}${this.btn('筛选')}</form><section id="alertRows" class="panel"></section><div id="pager" class="pager"></div>`;const load=async p=>{const d=await this.get('alerts?'+this.query({...query,page:p}));$('#alertRows').innerHTML=this.table(d.items.map(r=>({...r,metric:this.meta.metrics[r.metric]?.[0]||r.metric})),[['id','告警编号'],['turbine_id','风机'],['time','时间'],['metric','指标'],['value','实际值'],['normal_range','正常范围'],['level','等级'],['status','状态'],['handler','处理人'],['handled_at','处理时间'],['note','说明']],this.writable()?(r,i)=>`<button data-handle="${i}">处理</button>`:null);$$('[data-handle]').forEach(el=>el.onclick=()=>{const r=d.items[+el.dataset.handle];this.formDialog('处理告警',this.select('status','状态',['未处理','处理中','已处理'],false)+this.input('note','处理说明',r.note),async b=>{await this.get('alerts',{...b,id:r.id});await load(1)});$('#opsEdit [name=status]').value=r.status});this.pager(d,load)};this.bindForm('#alertFilter',async b=>{query=b;await load(1)});if($('#runDetection'))$('#runDetection').onclick=()=>this.action($('#runDetection'),async()=>{const r=await this.get('detect',{});$('#detectionResult').innerHTML=`<p class="notice">发现 ${r.total} 条异常，本次新增 ${r.created} 条告警。</p>`;await load(1)});await load(1)},
 async maintenance(){let query={};$('#opsBody').innerHTML=`<form id="workFilter" class="ops-filters">${this.select('kind','记录类型',['巡检','故障','维修'])}${this.btn('筛选')}${this.writable()?'<button type="button" class="primary" id="newWork">＋ 新增记录</button>':''}</form><section class="panel" id="workRows"></section><div id="pager" class="pager"></div>`;const load=async p=>{const d=await this.get('maintenance?'+this.query({...query,page:p}));$('#workRows').innerHTML=this.table(d.items,[['turbine_id','风机'],['kind','类型'],['time','时间'],['problem','问题'],['handler','处理人'],['method','处理方式'],['result','处理结果'],['status','状态']],this.writable()?(r,i)=>`<button data-editwork="${i}">修改</button>`:null);$$('[data-editwork]').forEach(el=>el.onclick=()=>this.editWork(d.items[+el.dataset.editwork]));this.pager(d,load)};this.bindForm('#workFilter',async b=>{query=b;await load(1)});if($('#newWork'))$('#newWork').onclick=()=>this.editWork();await load(1)},
 editWork(r={}){this.formDialog('运维记录',`<div class="form-row">${this.select('turbine_id','风机',this.meta.turbines,false)}${this.select('kind','类型',['巡检','故障','维修'],false)}${this.input('time','时间',r.time?.slice(0,16)||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),'datetime-local')}${this.select('status','状态',['处理中','已完成'],false)}</div>${this.input('problem','问题 / 巡检内容',r.problem)}${this.input('method','处理方式',r.method)}${this.input('result','结果',r.result||'待复核')}${this.input('notes','备注',r.notes||'','text',false)}`,async b=>{await this.get('maintenance',{...b,id:r.id});await this.maintenance()});if(r.id)for(const k of ['turbine_id','kind','status'])$('#opsEdit [name='+k+']').value=r[k]},
 async reports(){const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);$('#opsBody').innerHTML=`<form id="reportForm" class="ops-filters">${this.select('kind','报告类型',['运行日报','运行周报','故障统计报告','发电情况报告'],false)}${this.input('start','起始日期','','date',false)}${this.input('end','结束日期',today,'date')}${this.btn('生成报告','primary')}</form><div id="reportOutput"></div>`;const run=async b=>{const r=await this.get('reports?'+this.query(b));$('#reportOutput').innerHTML=`<section class="panel report-sheet"><div class="panel-title"><h2>${esc(r.title)}</h2><div><button id="reportCSV">导出 CSV</button><button id="reportPrint">打印</button></div></div><p>${r.start} — ${r.end} · 生成于 ${r.generated}</p><div class="quality-grid"><span>观测数据<b>${r.count}</b></span><span>参与风机<b>${r.turbines}</b></span><span>发电量 kWh<b>${this.num(r.energy_kwh)}</b></span><span>告警记录<b>${r.alerts.length}</b></span></div><h3>运行统计</h3>${this.table(Object.entries(r.stats).map(([k,v])=>({name:this.meta.metrics[k][0],...v})),[['name','指标'],['mean','均值'],['min','最小值'],['max','最大值'],['std','标准差']])}<h3>故障与告警</h3>${this.table(r.alerts,[['turbine_id','风机'],['time','时间'],['metric','指标'],['level','等级'],['status','处理状态']])}<h3>运维记录</h3>${this.table(r.maintenance,[['kind','类型'],['problem','问题'],['method','处理'],['result','结果']])}<h3>本期摘要</h3><p>${esc(r.conclusion)}</p></section>`;$('#reportPrint').onclick=()=>window.print();$('#reportCSV').onclick=()=>{const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';this.download(r.title+'.csv',[['报告',r.title],['期间',r.start+' - '+r.end],['发电量 kWh',r.energy_kwh],['数据量',r.count],[],['指标','均值','最小','最大','标准差'],...Object.entries(r.stats).map(([k,v])=>[this.meta.metrics[k][0],v.mean,v.min,v.max,v.std]),[],['告警风机','时间','指标','等级','状态'],...r.alerts.map(a=>[a.turbine_id,a.time,a.metric,a.level,a.status])].map(row=>row.map(quote).join(',')).join('\r\n'))}};this.bindForm('#reportForm',run);await run({kind:'运行日报',end:today})},
 async users(){const d=await this.get('users');$('#opsBody').innerHTML=`<button id="newUser" class="primary">＋ 新增用户</button><section class="panel">${this.table(d.items.map(r=>({...r,role_name:roles[r.role],enabled_text:r.enabled?'启用':'停用',farm_text:r.farms.join('、')})),[['username','账号'],['name','姓名'],['role_name','角色'],['farm_text','风场范围'],['enabled_text','状态']],(r,i)=>`<button data-useredit="${i}">编辑</button><button data-toggle="${i}">${r.enabled?'停用':'启用'}</button><button data-reset="${i}">重置密码</button><button data-userdelete="${i}">删除</button>`)}</section>`;$('#newUser').onclick=()=>this.editUser();$$('[data-useredit]').forEach(b=>b.onclick=()=>this.editUser(d.items[+b.dataset.useredit]));$$('[data-toggle]').forEach(b=>b.onclick=()=>this.action(b,async()=>{const r=d.items[+b.dataset.toggle];await this.get('users',{id:r.id,action:r.enabled?'disable':'enable'});await this.users()}));$$('[data-userdelete]').forEach(b=>b.onclick=()=>this.remove('users',d.items[+b.dataset.userdelete],()=>this.users()));$$('[data-reset]').forEach(b=>b.onclick=()=>{const r=d.items[+b.dataset.reset];this.formDialog('重置 '+r.username+' 的密码',this.input('password','新密码','','password'),async values=>{await this.get('users',{id:r.id,action:'reset',...values});await this.users()})})},
 editUser(r={}){this.formDialog(r.id?'修改用户':'新增用户',`${this.input('username','账号',r.username)}${this.input('name','姓名',r.name)}${r.id?'':this.input('password','初始密码（至少 6 位）','','password')}${this.select('role','角色',Object.entries(roles).map(([id,name])=>({id,name})),false)}<p>授权风场</p><div class="checks">${this.meta.farms.map(f=>`<label><input type="checkbox" name="farms" value="${esc(f.name)}" ${(!r.id||r.farms.includes(f.name))?'checked':''}>${esc(f.name)}</label>`).join('')}</div>`,async b=>{b.farms=[...$('#opsEdit').querySelectorAll('[name=farms]:checked')].map(x=>x.value);await this.get('users',{...b,id:r.id});await this.users()});if(r.id)$('#opsEdit [name=role]').value=r.role},
 async logs(){const d=await this.get('logs');$('#opsBody').innerHTML=`<section class="panel"><h3>最近 300 条重要操作</h3>${this.table(d.items,[['created','时间'],['actor','用户'],['role','角色'],['module','模块'],['action','操作'],['result','结果']])}</section>`},
 async preferences(){const p=this.meta.parameters;$('#opsBody').innerHTML=`<div class="chart-grid"><section class="panel"><h3>个人信息</h3><form id="profileForm">${this.input('name','显示姓名',state.user.name)}<p>账号 ${esc(state.user.username)} · ${roles[state.user.role]}</p>${this.btn('保存个人信息','primary')}</form></section><section class="panel"><h3>修改密码</h3><form id="changePassword">${this.input('old','原密码','','password')}${this.input('new','新密码（至少 10 位）','','password')}${this.input('confirm','再次确认新密码','','password')}${this.btn('更新密码','primary')}</form></section></div>${state.user.role==='admin'?`<section class="panel"><h3>系统基本参数</h3><form id="parameterForm">${this.input('platform_name','平台名称',p.platform_name)}<div class="form-row">${this.input('temperature_limit','告警温度上限 ℃',p.temperature_limit,'number')}${this.input('rpm_limit','转速上限 rpm',p.rpm_limit,'number')}${this.input('wind_limit','风速上限 m/s',p.wind_limit,'number')}</div>${this.btn('保存参数','primary')}</form></section>`:''}`;this.bindForm('#profileForm',async b=>{await this.get('profile',b);state.user.name=b.name;$('#userName').textContent=b.name;toast('个人信息已保存')});this.bindForm('#changePassword',async b=>{if(b.new!==b.confirm)throw Error('两次输入的密码不一致');await api('password',b);$('#changePassword').reset();toast('密码已更新，其他登录会话已退出')});if($('#parameterForm'))this.bindForm('#parameterForm',async b=>{await this.get('parameters',b);toast('参数已保存，下次检测生效')})}
};
